### PR TITLE
Timeout limits

### LINKED ISSUE #16: Trigger error when interactivity request fails
Related ticket: https://github.com/CartoDB/cartodb.js/issues/1717

When the user reaches its limits, interactivity could be affected, so the idea is to warn CARTO.js about that problem and then it should trigger that error accordingly.

### PR DESCRIPTION
**Pull request by nobuti**
This PR is related to https://github.com/CartoDB/cartodb.js/issues/1717. It fixes #16.

Because we are handling the grid.json as jsonp, it's not possible to send a `429` error, so we need to catch the error wrapped from the tiles.

### CODE REVIEW

File: control/lib/interaction.js [hunk 1]
```diff
@@ -93,7 +93,9 @@ wax.interaction = function() {
                     e: e
                 });
             } else {
-                bean.fire(interaction, 'off');
+                bean.fire(interaction, 'off', error && {
```
Comment (alonsogarciapablo) [inline control/lib/interaction.js]: I'd do the same in line 89 (`bean.fire(interaction, 'on'...`). If I recall correctly, `on` events are triggered when mouse is over a feature and `off` events are triggered when events are NOT passing over a feature. We want to include the error in both cases IMO.

Comment (nobuti) [reply control/lib/interaction.js]: But that scenario I think it's not possible. I mean, when there is a limit error, the gridjson doesn't contain any feature, only errors, see the line https://github.com/CartoDB/wax/pull/17/files#diff-296117891555ffc63dc0050305f266fcR112.

File: control/lib/gridmanager.js [hunk 2]
```diff
@@ -109,6 +109,7 @@ wax.gm = function() {
 
         wax.request.get(gurl, function(err, t) {
             if (err) return callback(err, null);
+            if (t.errors_with_context) return callback(t.errors_with_context, null);
```
Comment (dgaubert) [inline control/lib/gridmanager.js]: Sorry for being a PITA. But having `errors_with_context` array we can check `type` and `subtype` properties for each error. IMHO, we can go for some error categorization. can't we?

Comment (nobuti) [reply control/lib/gridmanager.js]: I thought this issue to make carto.js aware of every error on wax but I can change it.

Comment (dgaubert) [reply control/lib/gridmanager.js]: Oh! I just got it.

If Carto.js is responsible of categorizing them, it's perfect to yield error handling to Carto.js.

Sorry for the noise

File: control/lib/interaction.js (hunk 1 above)
Comment (alonsogarciapablo) [reply control/lib/interaction.js]: Makes sense 👍

**Review by pabletecodes — APPROVED** [review]

**Review by rubenmoya — APPROVED** [review]

**Comment by rubenmoya** [comment]
Closing this since we're removing wax in  wax in CartoDB/cartodb.js#1864

**Comment by rjimenezda** [comment]
Reopening because wax's not dead yet apparently
